-- Generated by pywal16 — rendered to ~/.cache/wal/colors-hyprland.lua
-- Consumed by ~/.config/hypr/config/theme.lua (hex values without '#',
-- which is the form Hyprland's rgba()/rgb() takes).
--
-- Generated with --cols16 dual, so colors 8-15 are distinct rather than copies
-- of 0-7; accent_bright below is color12, which under classic pywal was just a
-- copy of color4. See colors-fabric.css for the reasoning.
--
-- NOTE: lighten()/darken() take an integer percent — pywal16 strips '.' from
-- the argument, so `darken(0.3)` silently means 3%, not 30%. saturate() *sets*
-- saturation rather than adjusting it. Avoid it.
return {{
    background = "{background.strip}",
    foreground = "{foreground.strip}",
    cursor  = "{cursor.strip}",

    color0  = "{color0.strip}",
    color1  = "{color1.strip}",
    color2  = "{color2.strip}",
    color3  = "{color3.strip}",
    color4  = "{color4.strip}",
    color5  = "{color5.strip}",
    color6  = "{color6.strip}",
    color7  = "{color7.strip}",
    color8  = "{color8.strip}",
    color9  = "{color9.strip}",
    color10 = "{color10.strip}",
    color11 = "{color11.strip}",
    color12 = "{color12.strip}",
    color13 = "{color13.strip}",
    color14 = "{color14.strip}",
    color15 = "{color15.strip}",

    -- Semantic names, matching colors-fabric.css so the window borders and the
    -- shell panels are talking about the same colours.
    accent        = "{color4.strip}",
    accent_bright = "{color12.strip}",
    accent_hover  = "{color4.lighten(10).strip}",
    accent_active = "{color4.darken(10).strip}",
    inactive      = "{color8.strip}",
    surface       = "{background.lighten(6).strip}",
    border        = "{color8.darken(10).strip}",
}}
